[build]
builder = "NIXPACKS"
buildCommand = "npm run build background"



[deploy]
runtime = "V2"
healthcheckPath = "http://localhost:3002/health"
# restartPolicy = "ON_FAILURE"
restartPolicyMaxRetries = 2
# restartPolicyMaxDelay = 10
startCommand = "node dist/apps/background/main.js"