[build]
buildCommand = "pnpm run build background"



[deploy]
healthcheckPath = "http://localhost:3002/health"
# restartPolicy = "ON_FAILURE"
restartPolicyMaxRetries = 2
# restartPolicyMaxDelay = 10
startCommand = "node dist/apps/background/main.js"