export enum ENV {
  PORT = 'PORT',
  NODE_ENV = 'NODE_ENV',
  DATABASE_URL = 'DATABASE_URL',
  FRONTEND_URL = 'FRONTEND_URL',
  REDIS_URL = 'REDIS_URL',
  REDIS_KEY_PREFIX = 'REDIS_KEY_PREFIX',
  // JWT Configuration
  JWT_PRIVATE_KEY = 'JWT_PRIVATE_KEY',
  JWT_PUBLIC_KEY = 'JWT_PUBLIC_KEY',
  JWT_ACCESS_TOKEN_EXPIRES_IN = 'JWT_ACCESS_TOKEN_EXPIRES_IN',
  JWT_ISSUER = 'JWT_ISSUER',
  JWT_AUDIENCE = 'JWT_AUDIENCE',

  // Brevo Email Configuration
  BREVO_API_KEY = 'BREVO_API_KEY',
  BREVO_FROM_EMAIL = 'BREVO_FROM_EMAIL',
  BREVO_FROM_NAME = 'BREVO_FROM_NAME',

  // Company Information
  COMPANY_NAME = 'COMPANY_NAME',
  SUPPORT_EMAIL = 'SUPPORT_EMAIL',
  WEBSITE_URL = 'WEBSITE_URL',

  // Resend Email Configuration
  RESEND_API_KEY = 'RESEND_API_KEY',
  RESEND_FROM_EMAIL = 'RESEND_FROM_EMAIL',
  RESEND_FROM_NAME = 'RESEND_FROM_NAME',

  // Storage Configuration (S3)
  S3_ENDPOINT = 'S3_ENDPOINT',
  S3_REGION = 'S3_REGION',
  S3_ACCESS_KEY_ID = 'S3_ACCESS_KEY_ID',
  S3_SECRET_ACCESS_KEY = 'S3_SECRET_ACCESS_KEY',
  S3_PUBLIC_BUCKET = 'S3_PUBLIC_BUCKET',
  S3_PRIVATE_BUCKET = 'S3_PRIVATE_BUCKET',

  SUPER_ADMIN_EMAIL = 'SUPER_ADMIN_EMAIL',
  SUPER_ADMIN_PASSWORD = 'SUPER_ADMIN_PASSWORD',
  SUPER_ADMIN_FIRST_NAME = 'SUPER_ADMIN_FIRST_NAME',
  SUPER_ADMIN_LAST_NAME = 'SUPER_ADMIN_LAST_NAME',
  DISABLE_JOBS = 'DISABLE_JOBS',

  // Paystack Configuration
  PAYSTACK_SECRET_KEY = 'PAYSTACK_SECRET_KEY',
  PAYSTACK_PUBLIC_KEY = 'PAYSTACK_PUBLIC_KEY',
  PAYSTACK_WEBHOOK_SECRET = 'PAYSTACK_WEBHOOK_SECRET',
}
