export enum ENV {
  PORT = 'PORT',
  NODE_ENV = 'NODE_ENV',
  DATABASE_URL = 'DATABASE_URL',
  FRONTEND_URL = 'FRONTEND_URL',
  REDIS_URL = 'REDIS_URL',
  REDIS_KEY_PREFIX = 'REDIS_KEY_PREFIX',
  // JWT Configuration
  JWT_PRIVATE_KEY = 'JWT_PRIVATE_KEY',
  JWT_PUBLIC_KEY = 'JWT_PUBLIC_KEY',
  JWT_ACCESS_TOKEN_EXPIRES_IN = 'JWT_ACCESS_TOKEN_EXPIRES_IN',
  JWT_ISSUER = 'JWT_ISSUER',
  JWT_AUDIENCE = 'JWT_AUDIENCE',

  // Brevo Email Configuration
  BREVO_API_KEY = 'BREVO_API_KEY',
  BREVO_FROM_EMAIL = 'BREVO_FROM_EMAIL',
  BREVO_FROM_NAME = 'BREVO_FROM_NAME',

  // Company Information
  COMPANY_NAME = 'COMPANY_NAME',
  SUPPORT_EMAIL = 'SUPPORT_EMAIL',
  WEBSITE_URL = 'WEBSITE_URL',

  // Resend Email Configuration
  RESEND_API_KEY = 'RESEND_API_KEY',
  RESEND_FROM_EMAIL = 'RESEND_FROM_EMAIL',
  RESEND_FROM_NAME = 'RESEND_FROM_NAME',

  // Storage Configuration
  IDRIVE_ENDPOINT = 'IDRIVE_ENDPOINT',
  IDRIVE_REGION = 'IDRIVE_REGION',
  IDRIVE_ACCESS_KEY_ID = 'IDRIVE_ACCESS_KEY_ID',
  IDRIVE_SECRET_ACCESS_KEY = 'IDRIVE_SECRET_ACCESS_KEY',
  IDRIVE_PUBLIC_BUCKET = 'IDRIVE_PUBLIC_BUCKET',
  IDRIVE_PRIVATE_BUCKET = 'IDRIVE_PRIVATE_BUCKET',

  SUPER_ADMIN_EMAIL = 'SUPER_ADMIN_EMAIL',
  SUPER_ADMIN_PASSWORD = 'SUPER_ADMIN_PASSWORD',
  SUPER_ADMIN_FIRST_NAME = 'SUPER_ADMIN_FIRST_NAME',
  SUPER_ADMIN_LAST_NAME = 'SUPER_ADMIN_LAST_NAME',
  DISABLE_JOBS = 'DISABLE_JOBS',
}
