// Enums for employer verification document types and status

export enum EmployerDocumentType {
  GOVERNMENT_ISSUED_ID = 'GOVERNMENT_ISSUED_ID',
  UTILITY_BILL = 'UTILITY_BILL',
  CAC_REGISTRATION_CERTIFICATE = 'CAC_REGISTRATION_CERTIFICATE',
  OWNER_GOVERNMENT_ID = 'OWNER_GOVERNMENT_ID',
  DIRECTOR_GOVERNMENT_ID = 'DIRECTOR_GOVERNMENT_ID',
  SIGNED_LEGITIMATE_BUSINESS_DECLARATION = 'SIGNED_LEGITIMATE_BUSINESS_DECLARATION',
}

export enum GovernmentIdType {
  NIN_SLIP = 'NIN_SLIP',
  INTERNATIONAL_PASSPORT = 'INTERNATIONAL_PASSPORT',
  VOTERS_CARD = 'VOTERS_CARD',
}

export enum VerificationStatus {
  NOT_STARTED = 'NOT_STARTED',
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}
