export enum ENV {
  PORT = 'PORT',
  NODE_ENV = 'NODE_ENV',
  DATABASE_URL = 'DATABASE_URL',
  REDIS_URL = 'REDIS_URL',
  REDIS_KEY_PREFIX = 'REDIS_KEY_PREFIX',
  // JWT Configuration
  JWT_SECRET = 'JWT_SECRET',
  JWT_PRIVATE_KEY = 'JWT_PRIVATE_KEY',
  JWT_PUBLIC_KEY = 'JWT_PUBLIC_KEY',
  JWT_ACCESS_TOKEN_EXPIRES_IN = 'JWT_ACCESS_TOKEN_EXPIRES_IN',
  JWT_ISSUER = 'JWT_ISSUER',
  JWT_AUDIENCE = 'JWT_AUDIENCE',

  // Brevo Email Configuration
  BREVO_API_KEY = 'BREVO_API_KEY',
  BREVO_FROM_EMAIL = 'BREVO_FROM_EMAIL',
  BREVO_FROM_NAME = 'BREVO_FROM_NAME',

  // Company Information
  COMPANY_NAME = 'COMPANY_NAME',
  SUPPORT_EMAIL = 'SUPPORT_EMAIL',
  WEBSITE_URL = 'WEBSITE_URL',

  // Resend Email Configuration
  RESEND_API_KEY = 'RESEND_API_KEY',
  RESEND_FROM_EMAIL = 'RESEND_FROM_EMAIL',
  RESEND_FROM_NAME = 'RESEND_FROM_NAME',

  // Twilio SMS Configuration
  TWILIO_ACCOUNT_SID = 'TWILIO_ACCOUNT_SID',
  TWILIO_AUTH_TOKEN = 'TWILIO_AUTH_TOKEN',
  TWILIO_FROM_NUMBER = 'TWILIO_FROM_NUMBER',
}
