[build]
builder = "NIXPACKS"
buildCommand = "npm run build api"


[deploy]
runtime = "V2"
healthcheckPath = "http://localhost:3001/health"
# restartPolicy = "ON_FAILURE"
restartPolicyMaxRetries = 2
# restartPolicyMaxDelay = 10
startCommand = "node dist/apps/api/main.js"